exclude_paths:
- "node_modules/*"
- "bower_components/*"
- ".git/*"
- "test/*"
- "gulpfile.js"
- "karma.conf-ci.js"
- "karma.conf.js"
- "*.min.js"
- "*.min.css"
- "dist/*"
- "public/*"

engines:
  eslint:
    enabled: true

ratings:
  paths:
  - src/js/**/*.js
